<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-26">
<meta name="description" content="A retrieval and RAG system over 231,568 Amazon products and 6.75M reviews, rebuilt solo from a course project with measured design decisions, a test suite, and CI.">

<title>Smart Amazon Product Query Assistant – Data with Will</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/profile.jpg" rel="icon" type="image/jpeg">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4449642d44e59705cd9d6cbfdbfbdf56.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Data with Will</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../certifications.html"> 
<span class="menu-text">Certifications</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/canadasung" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/williamwnsong" target="_blank"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:canadasung@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Smart Amazon Product Query Assistant</h1>
  <div class="quarto-categories">
    <div class="quarto-category">NLP</div>
    <div class="quarto-category">RAG</div>
    <div class="quarto-category">LLM</div>
    <div class="quarto-category">BM25</div>
    <div class="quarto-category">Python</div>
    <div class="quarto-category">Semantic Search</div>
    <div class="quarto-category">FAISS</div>
    <div class="quarto-category">Streamlit</div>
    <div class="quarto-category">Information Retrieval</div>
    <div class="quarto-category">DuckDB</div>
  </div>
  </div>

<div>
  <div class="description">
    A retrieval and RAG system over 231,568 Amazon products and 6.75M reviews, rebuilt solo from a course project with measured design decisions, a test suite, and CI.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amz-query-demo0.png" class="img-fluid figure-img"></p>
<figcaption>Default view of the Amazon Product Search web app</figcaption>
</figure>
</div>
<section id="the-value-of-this-project-to-me" class="level3">
<h3 class="anchored" data-anchor-id="the-value-of-this-project-to-me">The value of this project to me</h3>
<ul>
<li><strong>Practicing and implementation</strong>:
<ul>
<li>information retrieval methods: BM25, Semantic Search, Hybrid</li>
<li>LLM-based AI Assistant</li>
<li>RAG (Retrieval-Augmented Generation)</li>
<li>real-time product recommendation system</li>
</ul></li>
<li><strong>Measurement and evaluation</strong>:
<ul>
<li>designing a 10-query evaluation set across difficulty tiers, then building a reproducible harness that regenerates every comparison table on demand.</li>
<li>quantifying <em>why</em> two retrieval methods disagree instead of asserting it: their top-5 results overlap on only 0.2 of 5 products on average.</li>
<li>running controlled experiments where one variable moves at a time, including a prompt comparison whose result contradicted my prediction.</li>
</ul></li>
<li><strong>Data quality investigation</strong>:
<ul>
<li>finding and quantifying three traps in the source data that would each have silently corrupted results, including a metadata field that is wrong for 73% of rows.</li>
<li>writing validation that asserts corpus invariants <em>before</em> a 25-minute indexing step, which caught two real bugs on its first run.</li>
</ul></li>
<li><strong>Engineering at scale</strong>:
<ul>
<li>scaling from 94k to 231,568 products, which required streaming ingest, schema-aware caching, and memory profiling.</li>
<li>building staleness guards so a search index can never be silently used against a corpus it was not built from.</li>
<li>146 tests, GitHub Actions CI, and root-causing a segfault from a macOS crash report.</li>
</ul></li>
<li><strong>Building LLM systems responsibly</strong>:
<ul>
<li>gating scope on a measured retrieval threshold in code, so off-topic questions are refused before any API call is made.</li>
<li>redacting contact details reviewers volunteered into review text, stripping them in the context builder so the model never receives them.</li>
<li>auditing the corpus for prompt injection, then declining to build the filter it seemed to call for, because all 40 matches were false positives.</li>
</ul></li>
<li><strong>Independent follow-through</strong>:
<ul>
<li>taking a graded team project and rebuilding it alone, deliberately, to understand each decision.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview">Overview</h3>
<p>A context-aware product search assistant for Amazon listings. Given a natural language query, it retrieves relevant products and generates an answer grounded in what reviewers actually wrote, showing the exact sources used.</p>
<p>This began as a two-person project for <strong>UBC MDS DSCI 575 (Advanced Machine Learning)</strong>, built with teammate Harrison Li. After the course ended I rebuilt it from scratch, expanding the corpus 2.5x and adding the engineering the original lacked. The goal was to understand every decision well enough to defend it with a measurement.</p>
<p>Almost every figure below is something I measured on the real corpus.</p>
</section>
<section id="project-repository" class="level3">
<h3 class="anchored" data-anchor-id="project-repository">Project repository</h3>
<p><strong>GitHub:</strong> <a href="https://github.com/canadasung/smart-amazon-product-query-assistant" target="_blank">smart-amazon-product-query-assistant</a></p>
<hr>
</section>
<section id="what-i-learned-with-evidence" class="level3">
<h3 class="anchored" data-anchor-id="what-i-learned-with-evidence">What I learned, with evidence</h3>
<p>Each item links to the full writeup in the repository.</p>
<section id="preprocessing-can-silently-destroy-a-query-before-any-model-sees-it" class="level4">
<h4 class="anchored" data-anchor-id="preprocessing-can-silently-destroy-a-query-before-any-model-sees-it">Preprocessing can silently destroy a query before any model sees it</h4>
<p>The query <code>quiet dishwasher for a small apartment under $400</code> returned a <strong>400 CFM range hood</strong>. Tracing it:</p>
<pre><code>'quiet dishwasher for a small apartment under $400'
   -&gt; ['quiet', 'dishwasher', 'small', 'apartment', '400']
   dropped: ['for', 'a', 'under']</code></pre>
<p><code>under</code> is a stopword and <code>$</code> is not alphanumeric, so BM25 searched for the bare number <code>400</code> with no notion of “less than”. The constraint was deleted during tokenization, before ranking began. Semantic search lost the same constraint differently, dissolving it into a 384-dimensional vector where no dimension means “price ceiling”.</p>
<p>The lesson generalized: when a result looks wrong, inspect what the pipeline actually received before suspecting the algorithm.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/docs/query-walkthrough.md" target="_blank">Full trace through all four retrieval modes</a></p>
</section>
<section id="three-data-traps-each-found-by-measuring-the-data" class="level4">
<h4 class="anchored" data-anchor-id="three-data-traps-each-found-by-measuring-the-data">Three data traps, each found by measuring the data</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Trap</th>
<th>Measured</th>
<th>Consequence if missed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>price</code> is null</td>
<td><strong>50.5%</strong> of products</td>
<td>Formatted naively it renders as the string <code>nan</code>, which BM25 then indexes as an ordinary searchable word across half the corpus</td>
</tr>
<tr class="even">
<td><code>main_category</code> is unreliable</td>
<td>only <strong>27.1%</strong> of products in the Appliances file are labelled “Appliances”</td>
<td>Category filtering would be wrong for 73% of rows</td>
</tr>
<tr class="odd">
<td><code>average_rating</code> is not the review mean</td>
<td>differs by &gt;0.1 for <strong>62,960 of 94,319</strong> products</td>
<td>It is Amazon’s site-wide figure; a document can show “4.4 stars” above reviews averaging 2.88</td>
</tr>
</tbody>
</table>
<p>The <code>nan</code> trap was the subtle one. It survives tokenizer cleaning, because <code>nan</code> looks exactly like a real word, so it had to be fixed at document construction instead.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/docs/amazon-reviews-2023.md" target="_blank">Dataset reference with all measurements</a></p>
</section>
<section id="two-retrieval-methods-that-barely-agree-quantified" class="level4">
<h4 class="anchored" data-anchor-id="two-retrieval-methods-that-barely-agree-quantified">Two retrieval methods that barely agree, quantified</h4>
<p>Across the 10-query evaluation set, BM25 and semantic search shared <strong>0.2 of their top 5 results on average</strong>. On most queries the overlap was zero.</p>
<p>That single number is the empirical case for hybrid retrieval: the methods are not better and worse versions of each other, they are complementary. It also reframed several results, because low overlap does not mean one system is wrong. On <code>something two people can play together on the couch</code> the two returned entirely different games and <strong>both answer sets were correct</strong>.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/results/milestone1_retrieval_comparison.md" target="_blank">Per-query retrieval comparison</a></p>
</section>
<section id="an-experiment-whose-result-contradicted-my-prediction" class="level4">
<h4 class="anchored" data-anchor-id="an-experiment-whose-result-contradicted-my-prediction">An experiment whose result contradicted my prediction</h4>
<p>I compared three prompt variants on identical retrieved context: a lightly-steered control, one with explicit anti-hallucination rules, and one that constrained only the <em>output shape</em>.</p>
<p>I expected the explicit rules to handle constraints best. The shape-constrained variant was strictest: it alone rejected a $39.99 game as not “under 40 dollars”. Forcing a NOT RECOMMENDED section appears to make the model adjudicate every candidate rather than mention only the easy ones.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/results/milestone2_discussion.md" target="_blank">Prompt comparison and RAG evaluation</a></p>
</section>
<section id="model-scale-improves-grounding-while-fluency-stays-flat" class="level4">
<h4 class="anchored" data-anchor-id="model-scale-improves-grounding-while-fluency-stays-flat">Model scale improves grounding while fluency stays flat</h4>
<p>Running an 8B and a 70B model on byte-identical context, both wrote fluent English. The 8B <strong>fabricated two prices</strong>: it claimed a $370 dishwasher was “above the $400 budget”, and that a $19.99 game was over a $40 budget when the real disqualifier was its platform. Both statements contradicted the context in its own prompt.</p>
<p>The usual RAG failure is a confident wrong fact. That drove two design decisions: the app shows a sources panel so any claim is checkable, and the context builder writes missing values explicitly as <code>price not listed</code>, because a model shown a gap will fill it.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/results/final_model_comparison.md" target="_blank">Model comparison on identical context</a></p>
</section>
<section id="scaling-the-corpus-was-an-engineering-problem" class="level4">
<h4 class="anchored" data-anchor-id="scaling-the-corpus-was-an-engineering-problem">Scaling the corpus was an engineering problem</h4>
<p>Going from 94k to 231,568 products broke naive approaches. What it actually required:</p>
<ul>
<li><strong>Streaming ingest.</strong> DuckDB reads 1.16 GB of gzipped JSONL at roughly 400 MB peak memory; loading it into pandas first would not fit comfortably.</li>
<li><strong>Schema-aware cache invalidation.</strong> Checking that a cached file has the right column <em>types</em> as well as the right names. A <code>price</code> column silently written as a string broke numeric filtering while every column name stayed correct.</li>
<li><strong>Corpus fingerprinting.</strong> Each index stores <code>categories@n_products#doc_text_sha</code> and refuses to load on a mismatch. The content hash catches an edit to document construction, which leaves the category list and product count identical. It costs 1.5 seconds against the 25 minutes it protects.</li>
<li><strong>Memory profiling.</strong> The BM25 index alone occupies 4.1 GB, which turned out to be the constraint that shapes any deployment plan.</li>
</ul>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/docs/design-decisions.md" target="_blank">Thirteen design decisions with the measurement behind each</a></p>
</section>
<section id="deciding-where-a-guardrail-belongs" class="level4">
<h4 class="anchored" data-anchor-id="deciding-where-a-guardrail-belongs">Deciding where a guardrail belongs</h4>
<p>The app answered “what’s 1+1?”. Retrieval had returned five arbitrary appliances, because top-k retrieval always returns k results however poor the match, so the emptiness check never fired and the model answered from its own knowledge.</p>
<p>The obvious fix is a prompt rule telling the model to decline. That rule takes effect only <strong>after the API call is billed</strong>, so I put the gate in Python: a threshold on the top-1 cosine, checked before retrieval runs.</p>
<p>Choosing the threshold took a measurement. Off-topic queries scored 0.31 to 0.376; the weakest <em>legitimate</em> query in my evaluation set scored 0.437. A threshold of 0.40 sits between them and classified 11 of 11 queries correctly. The margin is only 0.061, which is the honest caveat: vague-but-real questions and off-topic ones genuinely look alike to an embedding model, so I set the threshold low.</p>
<p>One subtlety made this harder than it looked. The score has to come from the semantic retriever directly, because <strong>neither fusion method preserves absolute scale</strong>: Reciprocal Rank Fusion emits <code>1/(60 + rank)</code>, so its top score is <code>1/61</code> whether a match is perfect or worthless, and weighted fusion min-max normalizes the top result to <code>1.0</code> by construction. Gating on a fused score would have let everything through while looking correct. A test now hands the gate a fused score of 1.0 alongside a cosine of 0.30 and asserts refusal, so a future simplification cannot quietly reintroduce the bug.</p>
<p>The same reasoning settled a privacy question. Reviewers had typed their own email addresses and phone numbers into review text: 282 and 112 documents respectively. A prompt rule saying “never repeat contact details” asks the model to hold the data and decline to use it. Stripping it in the context builder means the model never receives it, which is the stronger guarantee.</p>
</section>
<section id="knowing-which-defence-not-to-build" class="level4">
<h4 class="anchored" data-anchor-id="knowing-which-defence-not-to-build">Knowing which defence <em>not</em> to build</h4>
<p>Auditing the same corpus for prompt injection, 40 documents matched instruction-shaped phrases. Reading them, all 40 were ordinary English: “you are now a 4th grader”, “you are now a dryer technician”, and <code>system prompt</code> meaning a shell prompt. Zero were attacks.</p>
<p>That number argues against the defence it seems to invite. A regex filter shipped against this corpus would have run at a <strong>100% false-positive rate</strong>, silently degrading 40 legitimate products while catching nothing, and any paraphrase defeats it anyway.</p>
<p>Capability is what bounds injection risk. The model here has no tools, takes no actions, and its output renders as plain text, so the worst an injected review achieves is a bad recommendation. Writing that down changed how I think about agent design generally: the question worth asking is “what can this thing do if the rule fails”.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/docs/rag-concepts.md" target="_blank">Prompt injection, and what RAG creates</a></p>
<hr>
</section>
</section>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset">Dataset</h3>
<ul>
<li><strong>Source</strong>: <a href="https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023" target="_blank">Amazon Reviews 2023</a> (McAuley Lab, UCSD)</li>
<li><strong>Scale</strong>: <strong>231,568 products</strong> from <strong>6,753,220 reviews</strong>, spanning Appliances (94,319) and Video Games (137,249)</li>
<li><strong>Configurable</strong>: any of the dataset’s 34 categories can be selected at build time. Per-category intermediates are cached, so adding one re-downloads only that category.</li>
</ul>
<hr>
</section>
<section id="architecture" class="level3">
<h3 class="anchored" data-anchor-id="architecture">Architecture</h3>
<pre><code>query -&gt; (scope gate) -&gt; retrieve -&gt; build context -&gt; fill prompt -&gt; generate -&gt; answer + sources</code></pre>
<p>Four modes share one interface, so switching is a single argument:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Mode</th>
<th>Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>BM25</strong></td>
<td>Keyword matching with IDF, term-frequency saturation, and length normalization</td>
</tr>
<tr class="even">
<td><strong>Semantic</strong></td>
<td><code>all-MiniLM-L6-v2</code> embeddings, L2-normalized in a FAISS <code>IndexFlatIP</code> so inner product equals cosine similarity</td>
</tr>
<tr class="odd">
<td><strong>Hybrid</strong></td>
<td>Reciprocal Rank Fusion, <code>1/(60 + rank)</code>, or weighted score normalization</td>
</tr>
<tr class="even">
<td><strong>RAG</strong></td>
<td>Hybrid retrieval, then an LLM reads the reviews and applies constraints retrieval cannot enforce</td>
</tr>
</tbody>
</table>
<p>Because all three retrievers return <code>(parent_asin, score)</code>, the RAG pipeline is retriever-agnostic: semantic RAG and hybrid RAG differ by one argument and share the same pipeline.</p>
<p><strong>Models</strong>: <code>llama-3.3-70b-versatile</code> (primary) and <code>openai/gpt-oss-20b</code> (comparison), both via Groq, plus a local <code>llama3.1:8b</code> through Ollama for iterating without consuming API quota.</p>
<p><strong>Context is trimmed before it reaches the model.</strong> Whole documents produce 4,000 to 6,000 token contexts; title, metadata, and two truncated reviews produce about 600. An 85% reduction with no loss of answer quality, which moved the free-tier budget from roughly 22 to over 80 calls per day.</p>
<p><a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/docs/rag-concepts.md" target="_blank">How RAG works</a> and <a href="https://github.com/canadasung/smart-amazon-product-query-assistant/blob/main/docs/retrieval-concepts.md" target="_blank">how the retrievers work</a>, both written as learning notes.</p>
<hr>
</section>
<section id="evaluation" class="level3">
<h3 class="anchored" data-anchor-id="evaluation">Evaluation</h3>
<p>Evaluation runs as a script. <code>python src/evaluate.py</code> regenerates every comparison table, so changing a prompt or a retriever and re-running produces updated results automatically.</p>
<p>One deliberate choice: the qualitative rating columns are <strong>left blank</strong> by the generator. A model grading its own output is not an evaluation, so the script produces the evidence and I supply the verdicts. Each answer is printed alongside the exact sources the model was given, which makes the check concrete: a product named in an answer but absent from its sources is a fabrication.</p>
<hr>
</section>
<section id="engineering-practice" class="level3">
<h3 class="anchored" data-anchor-id="engineering-practice">Engineering practice</h3>
<ul>
<li><strong>146 tests</strong>, running in under 4 seconds with no network and no data files. They target the things that fail <em>silently</em>: tokenization, document construction, corpus invariants, fusion arithmetic, the staleness guards, and the safety gates.</li>
<li><strong>GitHub Actions CI</strong> running lint, format check, tests, and a check that every documented CLI still parses. The suite needs no secrets, which is why the workflow stays simple.</li>
<li><strong>Reproducibility treated as a real goal.</strong> The pipeline rebuilds from nothing with three commands, and tests pass on a machine with no NLTK corpus downloaded, verified by simulating one.</li>
<li><strong>Ruff</strong> for lint and formatting, pinned via <code>pyproject.toml</code> so results do not depend on whichever version happens to be on <code>PATH</code>.</li>
</ul>
<hr>
</section>
<section id="app" class="level3">
<h3 class="anchored" data-anchor-id="app">App</h3>
<p>A Streamlit app with two tabs. <strong>Search</strong> returns ranked products with category and price filters. <strong>RAG</strong> answers a question and displays the answer above the exact sources it was given.</p>
<section id="search-tab" class="level4">
<h4 class="anchored" data-anchor-id="search-tab">Search tab</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amz-query-demo1.png" class="img-fluid figure-img" style="width:100.0%" alt="Streamlit search tab showing five ranked oven products with fused scores, ratings, prices, and review snippets"></p>
<figcaption>Search tab: ranked results for ‘small and cheap ovens’ using hybrid retrieval, with fusion method, category, and price filters</figcaption>
</figure>
</div>
</section>
<section id="rag-tab" class="level4">
<h4 class="anchored" data-anchor-id="rag-tab">RAG tab</h4>
<p>The answer sits above the exact products the model was given. The caption records the retriever, model, prompt, context size, and stage timings, so any answer can be traced back to how it was produced.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amz-query-demo2.png" class="img-fluid figure-img" style="width:100.0%" alt="Streamlit RAG tab showing a generated recommendation citing prices and a review quote, above the source products"></p>
<figcaption>RAG tab answering ‘quiet dishwasher for a small apartment under $400’, with the generated answer above a Sources list of the five products supplied to the model</figcaption>
</figure>
</div>
<p>The line under the web-search checkbox reports the gate’s decision before generating, here <em>“will not search (the corpus can answer this without web results)”</em>.</p>
<p>Generation is gated behind an explicit submit button. Streamlit re-runs every tab’s body on every interaction, so an ungated LLM call would fire on any widget change and exhaust the daily API quota within minutes.</p>
<p>An optional web-search tool (Tavily) covers what a fixed 2023 snapshot cannot: current prices and availability. It is gated so it runs only when the question needs it, and results appear in a separate labelled block so web claims stay distinguishable from review evidence.</p>
<hr>
</section>
</section>
<section id="installation" class="level3">
<h3 class="anchored" data-anchor-id="installation">Installation</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/canadasung/smart-amazon-product-query-assistant.git</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> smart-amazon-product-query-assistant</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> env create <span class="at">-f</span> environment.yml</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> activate smart-amazon-query-assist</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> src/download_data.py     <span class="co"># download, merge, build documents</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> src/bm25.py              <span class="co"># keyword index</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> src/semantic.py          <span class="co"># FAISS index</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="ex">streamlit</span> run app/app.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Retrieval needs no API keys. The RAG features need a Groq key in <code>.env</code>; <code>.env.example</code> documents every variable.</p>
<hr>
</section>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways">Key takeaways</h3>
<ul>
<li><strong>Measure before asserting.</strong> Nearly every design decision here is defensible because a number backs it: the 0.2/5 retrieval overlap, the 50.5% null prices, the 85% context reduction, the 4.1 GB index. Each one changed what I built.</li>
<li><strong>The most expensive bugs are the silent ones.</strong> A <code>nan</code> in half the corpus, a price column typed as a string, a stale index serving confident wrong answers. None of them raised an error. That is why the project has validation, staleness guards, and tests aimed at exactly those paths.</li>
<li><strong>Be willing to be wrong in public.</strong> The prompt experiment contradicted my prediction, and saying so made the writeup more useful.</li>
<li><strong>Verification has to match the failure mode.</strong> Checking that a server returns HTTP 200 does not prove a query works. I learned that from a segfault my own testing had missed.</li>
<li><strong>Put the guarantee where it cannot be argued with.</strong> Leaving data out of the context is stronger than asking a model not to repeat it. The same reasoning moved scope checking into a threshold in code, where it also stops costing API quota.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/canadasung\.github\.io\/quarto-portfolio\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 William Song</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>