project:
  type: website
  output-dir: _site

website:
  title: "William's Data Science Portfolio"
  description: "Data scientist and analyst. MDS graduate from UBC."
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: resume.qmd
        text: Resume
    right:
      - icon: github
        href: https://github.com/canadasung
      - icon: linkedin
        href: https://linkedin.com/in/williamwnsong

  page-footer:
    left: "© 2026 William Song"
    center: "Built with [Quarto](https://quarto.org)"
    right: "[GitHub](https://github.com/canadasung/quarto-portfolio)"

format:
  html:
    theme:
      - cosmo
      - assets/custom.scss
    highlight-style: github
    code-fold: true
    code-tools: false
    toc: true
    toc-depth: 2
    smooth-scroll: true

execute:
  freeze: auto
