project:
  type: website
  output-dir: _site

website:
  title: "Data with Will"
  description: "William Song's Storytelling Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: certifications.qmd
        text: Certifications
      # - href: blog/index.qmd
      #   text: Blog
    right:
      - icon: github
        href: https://github.com/canadasung
      - icon: linkedin
        href: https://linkedin.com/in/williamwnsong
      - icon: instagram
        href: https://instagram.com/song.great.serenity

  page-footer:
    center: "© 2026 William Song"

format:
  html:
    theme:
      dark: 
        - darkly
        - assets/custom.scss
      light: 
        - cosmo
        - assets/custom.scss
    respect-user-color-scheme: true
    highlight-style: github
    code-fold: true
    code-tools: false
    toc: true
    toc-depth: 2
    smooth-scroll: true

execute:
  freeze: auto
