project:
  type: website
  output-dir: _site

website:
  title: "Data with Will"
  description: "William Song's Storytelling Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About
      # - href: projects/index.qmd
      #   text: Projects
      # - href: blog/index.qmd
      #   text: Blog
      # - href: resume.qmd
      #   text: Resume
    right:
      - icon: github
        href: https://github.com/canadasung
      - icon: linkedin
        href: https://linkedin.com/in/williamwnsong

  page-footer:
    center: "© 2026 William Song"

format:
  html:
    theme:
      - cosmo
      - assets/custom.scss
    highlight-style: github
    code-fold: true
    code-tools: false
    toc: true
    toc-depth: 2
    smooth-scroll: true

execute:
  freeze: auto
